name: Update AAGUIDs

on:
  workflow_dispatch:

jobs:
  update-aaguids:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          curl https://raw.githubusercontent.com/passkeydeveloper/passkey-authenticator-aaguids/main/combined_aaguid.json \
          | jq 'to_entries | [.[] | { key, value: .value.name }] | from_entries' \
          > aaguids.json
      - run: cat aaguids.json
      - run: |
          # check if aaguids.json changed
          if ! git status --porcelain aaguids.json | grep -q . ; then
            echo "Workspace is clean, skipping update."
            exit 0
          fi
          
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add aaguids.json
          git commit -m "update aaguids.json"
          git push
