name: Update AAGUIDs

on:
  workflow_dispatch:
    inputs:
      force-publish:
        type: boolean
        description: Try to publish even if aaguids.json did not change

jobs:
  update-aaguids:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build aaguids.json
        run: |
          curl https://raw.githubusercontent.com/passkeydeveloper/passkey-authenticator-aaguids/main/combined_aaguid.json \
          | jq 'to_entries | [.[] | { key, value: .value.name }] | from_entries' \
          > aaguids.json
      - name: aaguids.json
        run: cat aaguids.json
      - name: Check if aaguids.json changed
        id: check
        run: (git status --porcelain aaguids.json | grep -q .) && echo "changed=1" || echo "changed=0" >> "$GITHUB_OUTPUT"
      - name: Commit changes
        if: steps.check.outputs.changed == 1
        run: |
          # configure git user
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # commit changes
          git add aaguids.json
          git commit -m "update aaguids.json"
          
          # update package version
          npm version patch

          # push changes to repo
          git push
      - name: Publish to npm
        if: steps.check.outputs.changed == 1 || github.event.inputs.force-publish == 'true'
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --provenance
