name: Update AAGUIDs

on:
  schedule:
    - cron: '30 16 * * *'
  workflow_dispatch:
    inputs:
      force-publish:
        type: boolean
        description: Try to publish even if aaguids.json did not change

jobs:
  update-aaguids:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Build aaguids.json
        run: |
          curl https://raw.githubusercontent.com/passkeydeveloper/passkey-authenticator-aaguids/main/combined_aaguid.json \
          | jq 'to_entries | [.[] | { key, value: .value.name }] | from_entries' \
          > aaguids.json

      - name: aaguids.json
        run: cat aaguids.json

      - name: Check if aaguids.json changed
        id: check
        run: ((git status --porcelain aaguids.json | grep -q .) && echo "changed=true" || echo "changed=false") >> "$GITHUB_OUTPUT"

      - name: Setup git user
        if: steps.check.outputs.changed == 'true' || github.event.inputs.force-publish == 'true'
        run: |
          # configure git user
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Commit changes
        if: steps.check.outputs.changed == 'true'
        run: |
          git add aaguids.json
          git commit -m "update aaguids.json"

      - name: Bump version
        if: steps.check.outputs.changed == 'true' || github.event.inputs.force-publish == 'true'
        run: |
          # update package version
          npm version patch

          # push changes to repo
          git push --follow-tags

      - uses: actions/setup-node@v5
        if: steps.check.outputs.changed == 'true' || github.event.inputs.force-publish == 'true'
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        if: steps.check.outputs.changed == 'true' || github.event.inputs.force-publish == 'true'
        run: npm publish
